var age = 15;
console.log("Test 1: My age is 20");
console.log(age == 20);
var country = "Pakistan";
console.log("\nTest 2: Pakistan is the neighbour of Russia");
console.log(country == "russia");
var program = "VS code";
console.log("\nTest 3: I am working on Python ");
console.log(program == "python");
var laptop = "Dell";
console.log("\nTest 4: I have a Mac book");
console.log(laptop == "Mac book");
var mobile = "Nokia";
console.log("\n Test 5: I have a Realme mobile phone");
console.log(mobile == "Realme");
var water = "Aquafina";
console.log("\n Test 6: I do not drink tap water");
console.log(water == "Aquafina");
var fruit = "apple";
console.log("\n Test 7: I am eating apple ");
console.log(fruit == "apple");
var sport = "cricket";
console.log("/n Test 8: I play cricket regularly");
console.log(sport == "cricket");
var course = "IT";
console.log("/n Test 9: I am learning the course IT");
console.log(course == "IT");
var number = 100;
console.log("/n Test 10: Dividing 1000 by 10 gives the answer 100");
console.log(number == 100);
